;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Puzzle.Colour",NewTagName="Puzzle.Plate")
+GameplayTagList=(Tag="MixedColours.Box.Green",DevComment="")
+GameplayTagList=(Tag="MixedColours.Box.Orange",DevComment="")
+GameplayTagList=(Tag="MixedColours.Box.Purple",DevComment="")
+GameplayTagList=(Tag="Puzzle.Box.Blue",DevComment="")
+GameplayTagList=(Tag="Puzzle.Box.Green",DevComment="")
+GameplayTagList=(Tag="Puzzle.Box.Orange",DevComment="")
+GameplayTagList=(Tag="Puzzle.Box.Purple",DevComment="")
+GameplayTagList=(Tag="Puzzle.Box.Red",DevComment="")
+GameplayTagList=(Tag="Puzzle.Box.White",DevComment="")
+GameplayTagList=(Tag="Puzzle.Box.Yellow",DevComment="")
+GameplayTagList=(Tag="Puzzle.Colour.Blue",DevComment="")
+GameplayTagList=(Tag="Puzzle.Colour.Green",DevComment="")
+GameplayTagList=(Tag="Puzzle.Colour.Orange",DevComment="")
+GameplayTagList=(Tag="Puzzle.Colour.Purple",DevComment="")
+GameplayTagList=(Tag="Puzzle.Colour.Red",DevComment="")
+GameplayTagList=(Tag="Puzzle.Colour.White",DevComment="")
+GameplayTagList=(Tag="Puzzle.Colour.Yellow",DevComment="")

